# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='programinterface',
            options={'ordering': ('id',), 'verbose_name': 'Program interface', 'verbose_name_plural': 'Program interfaces'},
        ),
        migrations.AlterField(
            model_name='executionenvironment',
            name='exception_handling_policy',
            field=models.CharField(choices=[('IGNORE', 'Ignore'), ('INTERRUPT', 'Interrupt'), ('RAISE', 'Raise')], default='INTERRUPT', max_length=15, verbose_name='Exception handling policy'),
        ),
        migrations.AlterField(
            model_name='pythonmodulefunctiondefinition',
            name='module',
            field=models.CharField(default='__builtins__', max_length=255, verbose_name='Module name'),
        ),
        migrations.AlterField(
            model_name='stringconstant',
            name='value',
            field=models.TextField(default='', verbose_name='Value'),
        ),
    ]
