# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_sum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Result sum')),
            ],
            options={
                'verbose_name': 'Calculation',
                'verbose_name_plural': 'Calculations',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Car Type',
                'verbose_name_plural': 'Car Types',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Юридическое лицо', 'Legal Person'), ('Физическое лицо', 'Natural Person')], max_length=16, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Customer Type',
                'verbose_name_plural': 'Customer Types',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Возраст до 22 лет включительно, стаж до 3 лет включительно', 'age<=22, exp<=3'), ('Возраст старше 22 лет, стаж до 3 лет включительно', 'age>22, exp<=3'), ('Возраст до 22 лет включительно стаж свыше 3 лет', 'age<=22, exp>3'), ('Возраст старше 22 лет, стаж свыше 3 лет', 'age>22, exp>3')], max_length=16, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.AddField(
            model_name='calculation',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eosago.CarType', verbose_name='Car type'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='customer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eosago.CustomerType', verbose_name='Customer type'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='drivers',
            field=models.ManyToManyField(to='eosago.Driver', verbose_name='Drivers'),
        ),
    ]
