# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eosago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='title',
            field=models.CharField(choices=[('Возраст до 22 лет включительно, стаж до 3 лет включительно', 'age<=22, exp<=3'), ('Возраст старше 22 лет, стаж до 3 лет включительно', 'age>22, exp<=3'), ('Возраст до 22 лет включительно стаж свыше 3 лет', 'age<=22, exp>3'), ('Возраст старше 22 лет, стаж свыше 3 лет', 'age>22, exp>3')], max_length=64, verbose_name='Title'),
        ),
    ]
