# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eosago', '0002_auto_20171018_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='is_car_with_trailer',
            field=models.BooleanField(default=False, verbose_name='Is car with trailer?'),
        ),
        migrations.AddField(
            model_name='cartype',
            name='is_trailer_allowed',
            field=models.BooleanField(default=False, verbose_name='Is trailer option allowed?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='result_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Result sum'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='customertype',
            name='title',
            field=models.CharField(choices=[('Юридическое лицо', 'Legal Person'), ('Физическое лицо', 'Natural Person')], max_length=16, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='title',
            field=models.CharField(choices=[('Возраст до 22 лет включительно, стаж до 3 лет включительно', 'age<=22, exp<=3'), ('Возраст старше 22 лет, стаж до 3 лет включительно', 'age>22, exp<=3'), ('Возраст до 22 лет включительно стаж свыше 3 лет', 'age<=22, exp>3'), ('Возраст старше 22 лет, стаж свыше 3 лет', 'age>22, exp>3')], max_length=64, unique=True, verbose_name='Title'),
        ),
    ]
